[package]
name = "qrxfil"
version = "0.1.0"
authors = ["Jb DOYON <jb@jiby.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qrcode = "0.11"
base64 = "0.13.0"

[dev-dependencies]
test-temp-file = "0.1.2"
rand = "0.8.3"