[package]
name = "qrxfil"
version = "0.1.0"
authors = ["Jb DOYON <jb@jiby.tech>"]
license = "GPL-3.0-or-later"
readme = "README.org"
repository = "https://github.com/OverkillGuy/qrxfil/"
description = "Exfiltrate files via QR codes"


[dependencies]
qrcode = "0.12"
image = "0.23.13"
base64 = "0.13.0"
clap = {version = "2.33.3", features = ["yaml"]}

[dev-dependencies]
rand = "0.8.3"
assert_cmd = "1.0.3"
assert_fs = "1.0.1"
predicates = "1.0.7"
