[package]
name = "qrxfil"
version = "0.1.0"
authors = ["Jb DOYON <jb@jiby.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qrcode = "0.12"
image = "0.23.13"
base64 = "0.13.0"
clap = "3.0.0-beta.2"

[dev-dependencies]
rand = "0.8.3"
assert_cmd = "1.0.3"
assert_fs = "1.0.1"
predicates = "1.0.7"