#+TITLE: qrxfil

Exfiltrate files via QR codes.

Splits files across multiple QR codes for "sending" across air-gapped
computer systems. Generates numbered PNG files to scan.

The codes contain metadata about chunk number (e.g. "07 of 78") to
enable out-of-order scanning.



* Dependencies

=qrxfil= is built in Rust, relying on:
- [[https://crates.io/crates/base64][base64]], to encode binary in ASCII characters
- [[https://crates.io/crates/qrcode][qrcode]], to generate the codes themselves

This is a toy project meant to learn Rust, for which a Bash proof of
concept was built as reference, see the =scripts/= folder.


* Installation

Use =cargo deb= to generate a Debian package on linux that provides the
=qrxfil= command.

#+begin_src shell
cargo deb
sudo dpkg -i target/debian/qrxfil_0.1.0_amd64.deb
#+end_src

* Usage

To generate QR chunks for exfiltration:

#+begin_src shell
qrxfil exfil file_to_exfil.txt qr_output_folder/
#+end_src

Once these QR images are scanned (on your own), we can reconstruct the
file from a newline-delimited chunk file:

#+begin_src shell
qrxfil restore newline_delimited_chunks.txt restored_file.txt
#+end_src


* Development

Because =rust=, use =cargo= to build the binary

#+begin_src shell
cargo build
#+end_src

Run tests:

#+begin_src shell
cargo test
#+end_src

This project uses [[https://pre-commit.com/][pre-commit]] to enforce code guidelines.



* License

This project uses GPL-v3-or-later license, see file =COPYING=.
